
# bok
exec-once = regreet; hyprctl dispatch exit

monitor = , preferred, auto, 1

env = XCURSOR_SIZE,20
env = HYPRCURSOR_SIZE,20

misc {
	disable_hyprland_logo = true
	background_color = 0x000000
}

ecosystem {
	no_update_news = true
}
